permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2021
subtitle: Visitas 2021

num_years_crimson_existed: 146

monthly_page_views_millions: 1.3
yearly_page_views_millions: 16.8
yearly_page_time_spent_years: 58

google_doc_signup: https://docs.google.com/forms/d/e/1FAIpQLSeOis9koseUJtsMRrABikrl_-rJB3UTXffO2-YqzfcqusURHQ/viewform?usp=sf_link
facebook_rsvp_link: https://www.facebook.com/events/515215159346903/

president: Amanda Y. Su
managing_editor: James S. Bikales
business_manager: Melissa Du

arts:
  dir1:
    name: Sofia Andrade
    email: sofia.andrade@thecrimson.com
  dir2:
    name: Joseph P. Kelly
    email: joseph.kelly@thecrimson.com

blog:
  dir1:
    name: Janani Sekar
    email: janani.sekar@thecrimson.com
  dir2:
    name: Ellen S. Deng
    email: ellen.deng@thecrimson.com

business:
  dir1:
    name: Juliette B. Low Fleury
    email: juliette.lowfleury@thecrimson.com
  dir2:
    name: Samuel H. Carter
    email: samuel.carter@thecrimson.com

design:
  web:
    dir1:
      name: Victoria Ono
      email: victoria.ono@thecrimson.com
  illustration:
    dir1:
      name: Helen H. Wang
      email: helen.wang@thecrimson.com
  print:
    dir1:
      name: Meera S. Nair
      email: meera.nair@thecrimson.com
    dir2:
      name: Yuen Ting Chow
      email: yuenting.chow@thecrimson.com


editorial:
  dir1:
    name: Eleanor V. Wikstrom
    email: eleanor.wikstrom@thecrimson.com
  dir2:
    name: Marissa J. Joseph
    email: marissa.joseph@thecrimson.com

magazine:
  dir1:
    name: Maliya V. Ellis 
    email: maliya.ellis@thecrimson.com
  dir2:
    name: Garrett W. O'Brien 
    email: garrett.o'brien@thecrimson.com

news:
  dir1:
    name: Juliet E. Isselbacher
    email: juliet.isselbacher@thecrimson.com
  dir2:
    name: Michelle G. Kurilla
    email: michelle.kurilla@thecrimson.com

multimedia:
  dir1:
    name: Jenny Lu
    email: jenny.lu@thecrimson.com
  dir2:
    name: Jason Lam
    email: jason.lam@thecrimson.com

sports:
  dir1:
    name: Jasper G. Goodman
    email: jasper.goodman@thecrimson.com
  dir2:
    name: Noah Jun
    email: noah.jun@thecrimson.com

technology:
  dir1:
    name: Max Bobby
    email: max.bobby@thecrimson.com
  dir2:
    name: Chao Cheng
    email: chao.cheng@thecrimson.com
