permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2020
subtitle: Spring Comp 2020

num_years_crimson_existed: 146

monthly_page_views_millions: 1.3
yearly_page_views_millions: 14.6
yearly_page_time_spent_years: 58

google_doc_signup: https://forms.gle/5mKu582i859z7Dtw8
facebook_rsvp_link:

president: Aidan F. Ryan
managing_editor: Angela N. Fu
business_manager: Charlie B. Zhu

arts:
  dir1:
    name: Kalos K. Chu
    email: kalos.chu@thecrimson.com
  dir2:
    name: Joy C. Ashford
    email: joy.ashford@thecrimson.com

blog:
  dir1:
    name: Peyton A. Jones
    email: peyton.jones@thecrimson.com
  dir2:
    name: Rachel L. Reynolds
    email: rachel.reynolds@thecrimson.com

business:
  dir1:
    name: Owen F. Searle
    email: owen.searle@thecrimson.com
  dir2:
    name: Mark L. Xu
    email: mark.xu@thecrimson.com

design:
  web:
    dir1:
      name: Caitlin Lam
      email: caitlin.lam@thecrimson.com
    dir2:
      name: Jason Oh
      email: jason.oh@thecrimson.com
  illustration:
    dir1:
      name: Isabella C. Aslarus
      email: isabella.aslarus@thecrimson.com
  print:
    dir1:
      name: James S. Bikales
      email: james.bikales@thecrimson.com
    dir2:
      name: Cat D. Hyeon
      email: cat.hyeon@thecrimson.com

editorial:
  dir1:
    name: Guillermo S. Hava
    email: guillermo.hava@thecrimson.com
  dir2:
    name: Woojin Lim
    email: woojin.lim@thecrimson.com

magazine:
  dir1:
    name: Maya G. McDougall
    email: maya.mcdougall@thecrimson.com
  dir2:
    name: Olivia G. Oldham
    email: olivia.oldham@thecrimson.com

news:
  dir1:
    name: Ruth A. Hailu
    email: ruth.hailu@thecrimson.com
  dir2:
    name: Sanjana L. Narayanan
    email: sanjana.narayanan@thecrimson.com

multimedia:
  dir1:
    name: Naomi S. Castellon-Perez
    email: naomi.castellon-perez@thecrimson.com
  dir2:
    name: Amanda Y. Su
    email: amanda.su@thecrimson.com

sports:
  dir1:
    name: Lev Cohen
    email: lev.cohen@thecrimson.com
  dir2:
    name: James Joyce
    email: james.joyce@thecrimson.com

technology:
  dir1:
    name: Richard A. Xu
    email: richard.xu@thecrimson.com
  dir2:
    name: Zuzanna Skoczylas
    email: zuzanna.skoczylas@thecrimson.com
